.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:pyTooling-github| image:: https://img.shields.io/badge/pyTooling-pyTooling-323131?logo=github&longCache=true
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/pyTooling/pyTooling
.. |SHIELD:png:pyTooling-github| image:: https://raster.shields.io/badge/pyTooling-pyTooling-323131?logo=github&longCache=true
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/pyTooling/pyTooling

.. # Sourcecode license
.. |SHIELD:svg:pyTooling-src-license| image:: https://img.shields.io/pypi/l/pyTooling?logo=GitHub&label=code%20license
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:png:pyTooling-src-license| image:: https://img.shields.io/pypi/l/pyTooling?logo=GitHub&label=code%20license
   :alt: Code license
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:pyTooling-tag| image:: https://img.shields.io/github/v/tag/pyTooling/pyTooling?logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/tags
.. |SHIELD:png:pyTooling-tag| image:: https://raster.shields.io/github/v/tag/pyTooling/pyTooling?logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/tags

.. # GitHub release
.. |SHIELD:svg:pyTooling-release| image:: https://img.shields.io/github/v/release/pyTooling/pyTooling?logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/releases/latest
.. |SHIELD:png:pyTooling-release| image:: https://raster.shields.io/github/v/release/pyTooling/pyTooling?logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/releases/latest

.. # GitHub release date
.. |SHIELD:svg:pyTooling-date| image:: https://img.shields.io/github/release-date/pyTooling/pyTooling?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/releases
.. |SHIELD:png:pyTooling-date| image:: https://raster.shields.io/github/release-date/pyTooling/pyTooling?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:pyTooling-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyTooling
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/network/dependents
.. |SHIELD:png:pyTooling-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyTooling
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:pyTooling-gha-test| image:: https://img.shields.io/github/workflow/status/pyTooling/pyTooling/Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish?label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/actions?query=workflow%3A%22Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish%22
.. |SHIELD:png:pyTooling-gha-test| image:: https://img.shields.io/github/workflow/status/pyTooling/pyTooling/Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish?label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/actions?query=workflow%3A%22Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish%22

.. # Codacy - quality
.. |SHIELD:svg:pyTooling-codacy-quality| image:: https://img.shields.io/codacy/grade/08ef744c0b70490289712b02a7a4cebe?logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyTooling
.. |SHIELD:png:pyTooling-codacy-quality| image:: https://raster.shields.io/codacy/grade/08ef744c0b70490289712b02a7a4cebe?logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyTooling

.. # Codacy - coverage
.. |SHIELD:svg:pyTooling-codacy-coverage| image:: https://img.shields.io/codacy/coverage/08ef744c0b70490289712b02a7a4cebe?logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyTooling
.. |SHIELD:png:pyTooling-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/08ef744c0b70490289712b02a7a4cebe?logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyTooling

.. # Codecov - coverage
.. |SHIELD:svg:pyTooling-codecov-coverage| image:: https://img.shields.io/codecov/c/github/pyTooling/pyTooling
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/pyTooling
.. |SHIELD:png:pyTooling-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/pyTooling/pyTooling
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/pyTooling

.. # Libraries - source rank
.. |SHIELD:svg:pyTooling-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyTooling
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyTooling/sourcerank
.. |SHIELD:png:pyTooling-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyTooling
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyTooling/sourcerank

.. # PyPI tag
.. |SHIELD:svg:pyTooling-pypi-tag| image:: https://img.shields.io/pypi/v/pyTooling?logo=PyPI
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyTooling/
.. |SHIELD:png:pyTooling-pypi-tag| image:: https://raster.shields.io/pypi/v/pyTooling?logo=PyPI
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyTooling/

.. # PyPI project status
.. |SHIELD:svg:pyTooling-pypi-status| image:: https://img.shields.io/pypi/status/pyTooling?logo=PyPI
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:pyTooling-pypi-status| image:: https://raster.shields.io/pypi/status/pyTooling?logo=PyPI
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:pyTooling-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyTooling?logo=PyPI
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:pyTooling-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyTooling?logo=PyPI
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:pyTooling-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyTooling
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyTooling
.. |SHIELD:png:pyTooling-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyTooling
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyTooling

.. # Requires - status
.. |SHIELD:svg:pyTooling-req-status| image:: https://img.shields.io/requires/github/pyTooling/pyTooling
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/pyTooling/pyTooling/requirements/?branch=main
.. |SHIELD:png:pyTooling-req-status| image:: https://raster.shields.io/requires/github/pyTooling/pyTooling
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/pyTooling/pyTooling/requirements/?branch=main

.. # Documentation license
.. |SHIELD:svg:pyTooling-doc-license| image:: https://img.shields.io/badge/doc%20license-CC--BY%204.0-green
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:pyTooling-doc-license| image:: https://img.shields.io/badge/doc%20license-CC--BY%204.0-green
   :alt: Documentation License
   :height: 22
   :target: https://github.com/pyTooling/pyTooling/blob/main/doc/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:pyTooling-ghp-doc| image:: https://img.shields.io/badge/doc-read%20now%20%E2%9E%9A-blueviolet
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://pyTooling.github.io/pyTooling/
.. |SHIELD:png:pyTooling-ghp-doc| image:: https://img.shields.io/badge/doc-read%20now%20%E2%9E%9A-blueviolet
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://pyTooling.github.io/pyTooling/
